- php-typography/php-typography-debug.php
- readme.txt
- tests/class-hyphenator-test.php
- tests/class-php-typography-test.php
- wp-typography.php
Always use the clean_html function from php-typography-debug.php
> Tests: use only canonical clean_html function

- includes/class-wp-typography.php
Support for ACF (versio 4) and ACF Pro (version 5). Related to #57.
> ACF support

- includes/class-wp-typography-admin.php
- php-typography/php-typography-functions.php
> Translate language names

- includes/class-wp-typography.php
- php-typography/class-php-typography.php
- php-typography/php-typography-debug.php
Fix some coding standards violations
> Coding standards

- includes/class-wp-typography.php
> Ensure that wptexturize is off

- includes/class-wp-typography-admin.php
- includes/class-wp-typography-setup.php
- includes/class-wp-typography.php
- wp-typography.php
> Use object cache

- .gitignore
- readme.txt
> Meta improvements

- includes/class-wp-typography.php
> Fix to Settings API usage

- includes/class-wp-typography.php
When the Hyphenator instance is cached, the trie does not have to rebuilt on every request.
> Cache Hyphenator instance

- includes/class-wp-typography.php
Based on http://stackoverflow.com/a/1173769/6646342.
> Workaround for incorrect object cache unserialize behavior

- admin/partials/settings.php
- includes/class-wp-typography-admin.php
- includes/class-wp-typography.php
- php-typography/class-php-typography.php
- php-typography/class-settings.php
- tests/class-php-typography-test.php
- tests/class-settings-test.php
> Don't break numbered abbreviations

- .travis.yml
- includes/class-wp-typography-admin.php
- includes/class-wp-typography.php
- includes/settings/class-abstract-locale-settings.php
- includes/settings/class-basic-locale-settings.php
- includes/settings/class-locale-settings.php
- includes/settings/class-multilingual.php
- Support for multilingual plugins
- Enable language- or locale-specific default settings
> Multilingual support

- CHANGELOG.md
- includes/class-wp-typography.php
- readme.txt
- wp-typography.php
Reduces database load due to caching
> Version 5.0.3

- CHANGELOG.md
- README.md
- includes/class-wp-typography.php
- readme.txt
- wp-typography.php
Ensure that `WP_Typography::load_languages` always returns an array as promised.
> Release 5.0.4

- admin/partials/settings.php
- composer.lock
- includes/class-wp-typography.php
- includes/wp-typography/class-admin.php
- includes/wp-typography/class-options.php
- includes/wp-typography/class-setup.php
- includes/wp-typography/settings/class-abstract-locale-settings.php
- includes/wp-typography/settings/class-multilingual.php
- includes/wp-typography/settings/class-plugin-configuration.php
- includes/wp-typography/ui/class-checkbox-input.php
- includes/wp-typography/ui/class-control.php
- includes/wp-typography/ui/class-hidden-input.php
- includes/wp-typography/ui/class-input.php
- includes/wp-typography/ui/class-number-input.php
- includes/wp-typography/ui/class-sections.php
- includes/wp-typography/ui/class-select.php
- includes/wp-typography/ui/class-submit-input.php
- includes/wp-typography/ui/class-tabs.php
- includes/wp-typography/ui/class-textarea.php
- phpcs.xml
- tests/class-options-test.php
- tests/class-wp-typography-singleton-test.php
- tests/class-wp-typography-test.php
- tests/settings/class-plugin-configuration-test.php
- tests/ui/class-sections-test.php
- tests/ui/class-tabs-test.php
- wp-typography.php
> Refactor options handling

- admin/partials/settings.php
- composer.lock
- includes/class-wp-typography-factory.php
- includes/class-wp-typography.php
- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/components/class-public-interface.php
- includes/wp-typography/components/class-setup.php
- includes/wp-typography/data-storage/class-abstract-cache.php
- includes/wp-typography/data-storage/class-cache.php
- includes/wp-typography/data-storage/class-options.php
- includes/wp-typography/data-storage/class-transients.php
- includes/wp-typography/ui/class-checkbox-input.php
- includes/wp-typography/ui/class-control.php
- includes/wp-typography/ui/class-hidden-input.php
- includes/wp-typography/ui/class-input.php
- includes/wp-typography/ui/class-number-input.php
- includes/wp-typography/ui/class-select.php
- includes/wp-typography/ui/class-submit-input.php
- includes/wp-typography/ui/class-textarea.php
- tests/class-wp-typography-singleton-test.php
- tests/class-wp-typography-test.php
- tests/components/class-public-interface-test.php
- tests/components/class-setup-test.php
- tests/data-storage/class-abstract-cache-test.php
- tests/data-storage/class-cache-test.php
- tests/data-storage/class-options-test.php
- tests/data-storage/class-transients-test.php
> Rework caching classes

- admin/partials/settings/settings-page.php
- includes/class-wp-typography-factory.php
- includes/class-wp-typography.php
- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/components/class-common.php
- includes/wp-typography/components/class-multilingual-support.php
- includes/wp-typography/components/class-public-interface.php
- includes/wp-typography/components/class-setup.php
- includes/wp-typography/data-storage/class-transients.php
- includes/wp-typography/settings/class-abstract-locale-settings.php
- includes/wp-typography/settings/class-basic-locale-settings.php
- includes/wp-typography/settings/class-plugin-configuration.php
- includes/wp-typography/ui/class-checkbox-input.php
- includes/wp-typography/ui/class-control.php
- includes/wp-typography/ui/class-hidden-input.php
- includes/wp-typography/ui/class-input.php
- includes/wp-typography/ui/class-number-input.php
- includes/wp-typography/ui/class-sections.php
- includes/wp-typography/ui/class-select.php
- includes/wp-typography/ui/class-submit-input.php
- includes/wp-typography/ui/class-tabs.php
- includes/wp-typography/ui/class-textarea.php
- tests/class-testcase.php
- tests/class-wp-typography-test.php
- tests/data-storage/class-transients-test.php
- Small style fixes.
- Tighter cohesion for `WP_Typography`.
- Update version to 5.1.0-beta.2
> Miscellaneous code clean-ups

- .phpstan.neon
- CHANGELOG.md
- composer.json
- composer.lock
- readme.txt
- wp-typography.php
- Composer requirements updated.
- CHANGELOG updated.
- README updated.
> Update CHANGELOG and README for 5.1.0

- CHANGELOG.md
- includes/wp-typography/components/class-public-interface.php
- readme.txt
- tests/components/class-public-interface-test.php
- wp-typography.php
> Release version 5.1.1 to fix text widget shortcodes on WP 4.8+

- CHANGELOG.md
- composer.lock
- includes/wp-typography/components/class-multilingual-support.php
- readme.txt
- tests/components/class-multilingual-support-test.php
- tests/components/class-public-interface-test.php
- wp-typography.php
*   _Change_: Updated to use version 5.2.3 of the composer package `mundschenk-at/php-typography`.
*   _Bugfix_: Sometimes, the French double quotes style generated spurious ».
*   _Bugfix_: Locale-based language files where not properly matched (primarily affecting `en-US` and `en-GB`, props @strasis).
> Release 5.1.3

- .travis.yml
- composer.json
- composer.lock
- includes/class-wp-typography-requirements.php
- includes/wp-typography/data-storage/class-transients.php
- includes/wp-typography/settings/class-basic-locale-settings.php
- includes/wp-typography/ui/class-select.php
- tests/class-wp-typography-requirements-test.php
- tests/ui/class-control-test.php
- Fix PHP 7.2 behavior
- Fix Travis for all PHP versions
> Fix PHP 7.2 behavior with __PHP_Incomplete_Class

- includes/wp-typography/components/class-multilingual-support.php
- includes/wp-typography/settings/class-abstract-locale-settings.php
- includes/wp-typography/settings/class-basic-locale-settings.php
- includes/wp-typography/settings/class-locale-settings.php
- tests/components/class-multilingual-support-test.php
Fixes #186.
- Add language aliases for language matching.
- Add locale aliases for language matching.
- Test coverage for these changes.
> Language aliases

- CHANGELOG.md
- includes/class-wp-typography.php
- includes/wp-typography/components/class-public-interface.php
- readme.txt
- tests/class-wp-typography-test.php
- tests/components/class-public-interface-test.php
- wp-typography.php
*   _Bugfix_: Languages were not sorted correctly in the settings page.
*   _Bugfix_: Circular references in caches objects have been fixed.
*   _Bugfix_: Workaround for Divi theme crash, avoiding `get_body_class()`.
> Release 5.2.1

- .scrutinizer.yml
- CHANGELOG.md
- composer.json
- package-lock.json
- package.json
- readme.txt
- wp-typography.php
Missing partial in version check component added.
> Release 5.2.3

- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/components/class-multilingual-support.php
- includes/wp-typography/components/class-public-interface.php
- includes/wp-typography/components/class-setup.php
- tests/components/class-setup-test.php
Fix some issues identified by Scrutinizer
> Miscellaneous Clean-ups

- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/components/class-multilingual-support.php
- includes/wp-typography/components/class-public-interface.php
- includes/wp-typography/components/class-setup.php
- tests/components/class-setup-test.php
> Release 5.2.4

- includes/class-wp-typography-factory.php
- includes/wp-typography/components/class-common.php
- includes/wp-typography/components/class-public-interface.php
- includes/wp-typography/integration/class-acf-integration.php
- includes/wp-typography/integration/class-container.php
- includes/wp-typography/integration/class-plugin-integration.php
- includes/wp-typography/integration/class-woocommerce-integration.php
- tests/components/class-common-test.php
- tests/components/class-public-interface-test.php
- tests/integration/class-acf-integration-test.php
- tests/integration/class-container-test.php
- tests/integration/class-woocommerce-integration-test.php
Fixes #194.
- Refactor plugin integrations to separate classes.
- Actually enable ACF support with the current free plugin (version 4).
- Add granular control for individual fields via the the ACF settings API (version 5 only).
> Enhanced ACF support

- CHANGELOG.md
- readme.txt
- wp-typography.php
Update README & Changelog for the release of 5.3.0.
> Release 5.3.0

- CHANGELOG.md
- includes/wp-typography/components/class-setup.php
- readme.txt
- tests/components/class-setup-test.php
- wp-typography.php
Fixes #208 .
- Clear cache on update and not only on initial activation.
- Update version number to 5.3.1.
> Release 5.3.1

- .scrutinizer.yml
- CHANGELOG.md
- composer.json
- readme.txt
- tests/data-storage/class-transients-test.php
- wp-typography.php
- Fixes a Smart Fractions bug by including a newer version of `mundschenk-at/php-typography`.
- Allows PHPUnit 7.x for testing.
- Runs JavaScript checks on Scrutinizer.
> Release 5.3.3

- CHANGELOG.md
- composer.json
- package-lock.json
- package.json
- readme.txt
- wp-typography.php
- Update version to 5.3.4
- Update library dependencies.
> Release 5.3.4

- CHANGELOG.md
- composer.json
- package-lock.json
- package.json
- readme.txt
- wp-typography.php
- Update to `mundschenk-at/php-typography` to fix two bugs:
- _Bugfix_: 50/50 (and x/x except 1/1) are not treated as fractions anymore.
- _Bugfix_: The French spacing rules were not applied to closing guillemets followed by a comma.
> Release 5.3.5

- CHANGELOG.md
- includes/wp-typography/integration/class-acf-integration.php
- package-lock.json
- package.json
- readme.txt
- tests/integration/class-acf-integration-test.php
- wp-typography.php
> Release 5.4.2

- CHANGELOG.md
- includes/wp-typography/class-implementation.php
- includes/wp-typography/components/class-multilingual-support.php
- package-lock.json
- package.json
- readme.txt
- tests/class-wp-typography-implementation-test.php
- tests/components/class-multilingual-support-test.php
- wp-typography.php
- Language detection for locales without a country code (fixes #243).
- Default values are set for newly added options (fixes #242).
> Release 5.5.4

- CHANGELOG.md
- includes/wp-typography/settings/class-plugin-configuration.php
> Add support for international dash style without hairspaces

- includes/class-wp-typography-factory.php
- includes/class-wp-typography.php
- includes/wp-typography/class-implementation.php
- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/components/class-common.php
- includes/wp-typography/components/class-multilingual-support.php
- includes/wp-typography/components/class-public-interface.php
- includes/wp-typography/components/class-setup.php
- includes/wp-typography/data-storage/class-transients.php
- includes/wp-typography/integration/class-acf-integration.php
- includes/wp-typography/settings/class-basic-locale-settings.php
- includes/wp-typography/settings/class-plugin-configuration.php
- tests/bootstrap.php
- tests/class-wp-typography-factory-test.php
- tests/class-wp-typography-implementation-test.php
- tests/class-wp-typography-test.php
- tests/components/class-admin-interface-test.php
- tests/components/class-public-interface-test.php
- tests/components/class-setup-test.php
- wp-typography.php
- Add missing global namespace to function calls.
- Add missing global namespace to used constants.
- Use new constant `\WP_TYPOGRAPHY_PLUGIN_FILE` instead of passing the path of the main plugin file as a parameter.
> Various PHP housekeeping tasks

- .scoper.inc.php
- CHANGELOG.md
- Gruntfile.js
- includes/wp-typography/settings/class-plugin-configuration.php
- package.json
- readme.txt
- wp-typography.php
- Update version.
- Update CHANGELOG/README for 5.6.0.
- Fix scoping bug.
- Slightly shorten user-visible name for new dash style.
> Finalize release 5.6.0

- .scoper.inc.php
- CHANGELOG.md
- Gruntfile.js
- composer.json
- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/components/class-public-interface.php
- package.json
- phpcs.xml
- readme.txt
- tests/components/class-public-interface-test.php
- wp-typography.php
- Makes parsing more robust when encountering `DOMDocument` errors.
- Updates coding standards for changes in WPCS.
- Build process is updated to use `vendor-scoped/` for dependencies.
- Fixes incorrect usage of `plugin_dir_url()` (fixes #269).
> Release 5.6.1

- tests/class-wp-typography-implementation-test.php
- Remove reference to non-existing method in test case coverage annotation.
> Fix test coverage metrics

- .gitignore
- Gruntfile.js
- composer.json
- includes/wp-typography/class-implementation.php
- package.json
- phpcs.xml
- tests/class-plugin-controller-test.php
- tests/class-testcase.php
- tests/class-wp-typography-factory-test.php
- tests/class-wp-typography-implementation-test.php
- tests/class-wp-typography-singleton-test.php
- tests/class-wp-typography-test.php
- tests/components/class-admin-interface-test.php
- tests/components/class-common-test.php
- tests/components/class-multilingual-support-initialization-test.php
- tests/components/class-multilingual-support-test.php
- tests/components/class-public-interface-test.php
- tests/components/class-setup-test.php
- tests/data-storage/class-cache-test.php
- tests/data-storage/class-options-test.php
- tests/data-storage/class-transients-test.php
- tests/integration/class-acf-integration-test.php
- tests/integration/class-container-test.php
- tests/integration/class-woocommerce-integration-test.php
- tests/settings/class-abstract-locale-settings-test.php
- tests/settings/class-plugin-configuration-test.php
- tests/typography/class-custom-node-fix-test.php
- tests/typography/class-custom-token-fix-test.php
- tests/ui/class-sections-test.php
- tests/ui/class-tabs-test.php
- Update Grunt packages.
- Use latest coding standards.
- Ignore Atom/Serenata files.
- Allow/use never versions of PHPUnit.
> Update development infrastructure

- CHANGELOG.md
- readme.txt
- Adds missing release date.
- Removes old CHANGELOG entries from `readme.txt`.
> Fix CHANGELOG for release 5.7.0

- .github/workflows/ci.yml
- Adds a GitHub workflow for CI (instead of Travis)
> Meta: Add GitHub actions for CI

- CHANGELOG.md
- Gruntfile.js
- composer.json
- js/clean-clipboard.js
- js/clean-clipboard.min.js
- readme.txt
- wp-typography.php
- Bumps version and stable version to 5.8.0.
- Updates CHANGELOG.
- Updates generated JS.
- Fixes small bug in phpcs script.
> Release 5.8.0

- .scoper.inc.php
- CHANGELOG.md
- js/src/clean-clipboard.js
- readme.txt
- wp-typography.php
> Release 5.8.1

- .github/workflows/ci.yml
- Gruntfile.js
- composer.json
- includes/wp-typography/integration/class-acf-integration.php
- js/clean-clipboard.js
- js/clean-clipboard.min.js
- package.json
- tests/integration/class-acf-integration-test.php
- wp-typography.php
- Updates Composer dependencies.
- Updates NPM dependencies.
- Fixes build process.
- Updates copyright years.
- Changes main branch to `main` in CI workflow.
> Housekeeping

- CHANGELOG.md
- includes/wp-typography/settings/class-plugin-configuration.php
- Changes the default of `Prevent widows` to `false` to forestall complaints about missing hyphenation in headings.
> Change dewidowing default

- CHANGELOG.md
- includes/wp-typography/integration/class-acf-integration.php
- readme.txt
- tests/integration/class-acf-integration-test.php
- wp-typography.php
- Do not change return type of ACF fields (potentially breaking downstream code).
> Release 5.9.1

- admin/partials/settings/settings-page.php
- includes/wp-typography/class-factory.php
- includes/wp-typography/components/class-admin-interface.php
- includes/wp-typography/ui/class-template.php
- tests/components/class-admin-interface-test.php
- tests/ui/class-template-test.php
- Adds a helper object for including partial templates.
> Add partials helper

- CHANGELOG.md
- composer.json
- includes/wp-typography/class-implementation.php
- readme.txt
- tests/class-wp-typography-implementation-test.php
- tests/components/class-block-editor-test.php
- tests/components/class-setup-test.php
- tests/data-storage/class-cache-test.php
- wp-typography.php
Fixes #337.
- Updates dependencies.
- Updates method calls fore new signatures in dependencies.
- Updates README and CHANGELOG.
- Bumps version to `5.11.0`.
> Fix PHP 8.3 error when requirements are not met
