mundschenk-at/wp-typography

php-typography/class-php-typography.php
tests/class-php-typography-test.php

Make smart_fractions and prime symbols play nice together

---

php-typography/class-hyphenator.php
phpunit.xml
tests/class-hyphenator-test.php
tests/class-php-typography-test.php

Generate proper patterns for custom hyphenations and honor the `min_after` setting (was off by one). Fixes #62.

Fix custom hyphenations

---

includes/class-wp-typography.php
php-typography/bin/class-pattern-converter.php
php-typography/bin/pattern2json.php
php-typography/class-dom.php
php-typography/class-settings.php
php-typography/class-strings.php

* Use `\PHP_Typography\Strings::uchr` from the WordPress side, too.
* Make `\PHP_Typography\Strings` and `\PHP_Typography\DOM` abstract classes.
* Fix a few missed `array()` declarations.

Various fixes

---

tests/class-hyphenator-test.php
tests/class-php-typography-test.php

With the new pattern file, "Sauerstoff" is now hyphenated "Sauer|stoff" (before a9de79ba4817ff0a9d25ea961c703a25bafd7930: "Sau|er|stoff"). 
Not sure if that is intentional by the upstream pattern maintainers.

Fix tests for updated German pattern file.

---

composer.json
composer.lock
includes/class-wp-typography.php
tests/class-wp-typography-test.php

- Update PHP-Typography to 5.2.0.
- Provide access to the "use true narrow space" setting.

Update PHP-Typography to 5.2.0

---

includes/class-wp-typography.php
includes/wp-typography/components/class-common.php
includes/wp-typography/components/class-multilingual-support.php
includes/wp-typography/ui/class-control.php
tests/class-wp-typography-singleton-test.php
tests/class-wp-typography-test.php
tests/components/class-common-test.php
tests/components/class-multilingual-support-test.php

- Extract `init` action common to both admin and public interfaces to new component `Common`.
- Adapt unit tests accordingly.

Extract common component

---

includes/class-wp-typography.php
includes/wp-typography/components/class-admin-interface.php
tests/class-wp-typography-test.php
tests/components/class-admin-interface-test.php

- Delete the helper options `RESTORE_DEFAULTS` and `CLEAR_CACHE` instead of setting them to `false`.
- Prevent duplicate admin notices (https://core.trac.wordpress.org/ticket/21989).

Delete RESTORE_DEFAULTS and CLEAR_CACHE options instead of setting them to false

---

includes/class-wp-typography-factory.php
includes/class-wp-typography.php
includes/wp-typography/class-implementation.php
includes/wp-typography/class-plugin-controller.php
includes/wp-typography/components/class-admin-interface.php
includes/wp-typography/components/class-multilingual-support.php
tests/class-plugin-controller-test.php
tests/class-wp-typography-imlementation-test.php
tests/class-wp-typography-singleton-test.php
tests/class-wp-typography-test.php
tests/components/class-admin-interface-test.php
tests/components/class-multilingual-support-test.php
wp-typography.php

Fixes #196.
- `WP_Typography` becomes a pure facade for the `PHP_Typography` API.
- Deprecate the static wrapper functions in favor of magic method overriding (e.g. allowing `process` to be called statically).
- Move implementation to new class `WP_Typography\Implementation` to allow static and non-static calls to the same method names.

Split WP_Typography between API facade, API implementation and Plugin Controller

---

includes/wp-typography/class-implementation.php
includes/wp-typography/typography/class-custom-node-fix.php
includes/wp-typography/typography/class-custom-registry.php
includes/wp-typography/typography/class-custom-token-fix.php
tests/class-wp-typography-implementation-test.php
tests/typography/class-custom-node-fix-test.php
tests/typography/class-custom-registry-test.php
tests/typography/class-custom-token-fix-test.php

Fixes #217, fixes #218.
- New filter hooks `typo_custom_{$group}_node_fix` for custom node fixes.
- New filter hook `typo_custom_token_fix` for custom token fixes.-

Add hooks to allow for custom node manipulation

---

CHANGELOG.md
includes/wp-typography/components/class-public-interface.php
includes/wp-typography/integration/class-container.php

Fixes #229.
- Content filters are disabled during WP-CLI commands.

No content filtering while running WP-CLI commands

---

CHANGELOG.md
composer.json
readme.txt
wp-typography.php

*   _Bugfix_: Parts of hyphenated words should not be detected as Roman numerals anymore.
*   _Bugfix_: The Unicode hyphen character (‐) is recognized as a valid word combiner.

Release 5.5.1

---

CHANGELOG.md
includes/wp-typography/components/class-public-interface.php
tests/components/class-public-interface-test.php
tests/settings/class-tools-test.php

Fixes #246.
- Removed the `title` variant of `typo_disable_filtering`.
- HTML markup in `<title>` is now prevented by not filtering certain hooks that would not expect HTML.

Refactor title filters

---

CHANGELOG.md
includes/wp-typography/settings/class-plugin-configuration.php

Fixes #252.
- Ampersands, all-caps words, and initial quotes are no longer wrapped in `<span>` by default.

Disable CSS hook injection by default

---

CHANGELOG.md
includes/wp-typography/class-implementation.php
includes/wp-typography/settings/class-plugin-configuration.php
includes/wp-typography/ui/class-sections.php
tests/class-wp-typography-implementation-test.php

Fixes #253.
- Adds character remapping settings to the General Scope tab.
- Deprecates the specialized `typo_narrow_no_break_space` filter hook.
- Updates the unit tests.

Add GUI for special character remapping

---

.scoper.inc.php
.travis.yml
Gruntfile.js
composer.json
package.json

- All dependencies except the core `PHP_Typography` package get moved under `WP_Typography\Vendor`.
- The build system has been updated.
- Browser-prefixing uses the new-style configuration.

Scope third-party dependencies 

---

Gruntfile.js
composer.json
package.json

- Moves `vendor/`directory to `vendor-scoped/` to make sure GlotPress picks up the strings.
- Updates Grunt dependencies.

Scope vendor directory

---

.scrutinizer.yml
.travis.yml

- Scrutinizer-CI analysis runs on PHP 7.4.
- Travis tests run on PHP 7.3 and PHP 7.4.

Update integration tooling to use PHP 7.3 and PHP 7.4

---

includes/class-wp-typography-factory.php
includes/class-wp-typography-requirements.php
includes/wp-typography/components/class-admin-interface.php
tests/bootstrap.php
tests/class-wp-typography-requirements-test.php
wp-typography.php

Fixes #266.
- Adds a check that the DOM extension is activated.
- Introduces `WP_TYPOGRAPHY_PLUGIN_PATH` constant.
- Bumps version to `5.7.0-alpha.1`.

Check for DOM extension

---

composer.json
includes/class-wp-typography-factory.php
includes/wp-typography/exceptions/class-object-factory-exception.php
phpcs.xml
phpunit.xml
readme.txt
tests/bootstrap.php
tests/class-wp-typography-factory-test.php
wp-typography.php

Fixes #292, #109.
- Updates `Dice\Dice` to `4.0.2` with custom patches for backwards compatibility with PHP 7.x.
- Bumps plugin version to `5.8.0-alpha.1`.
- Bumps PHP requirements to at least 7.0.
- Works around Xdebug issue by changing PHPunit configuration.

Basic PHP 8.x compatibility

---

CHANGELOG.md
includes/wp-typography/integration/class-acf-integration.php
tests/integration/class-acf-integration-test.php

Fixes #305.
- Adds support for ACF 6+.
- Adds support for the `array` return type.

Support Advanced Custom Fields 6

---

.github/workflows/ci.yml

- Updates `actions/cache` and `actions/checkout` to `v3`.
- Uses `ubuntu-22.04` for the action runners.

Fix GitHub Actions warnings

---

.github/workflows/ci.yml
composer.json
includes/class-wp-typography.php
includes/wp-typography/class-implementation.php
includes/wp-typography/components/class-multilingual-support.php
includes/wp-typography/typography/class-custom-token-fix.php

- Runs CI tasks on PHP 8.3, experimental on PHP 8.4.
- Fixes build task to work on PHP 8.4.
- Fixes PHP 8.4 code deprecations (but not yet in `php-typography`).

Add preliminary support for PHP 8.4

---

includes/wp-typography/components/class-public-interface.php
tests/components/class-public-interface-test.php

Fixes #315.
- Don't print styles when `STYLE_CSS_INCLUDE` is false.

Don't print styles when STYLE_CSS_INCLUDE is disabled

---

includes/class-wp-typography.php
includes/wp-typography/class-implementation.php
includes/wp-typography/components/class-admin-interface.php
includes/wp-typography/components/class-multilingual-support.php
tests/class-wp-typography-implementation-test.php
tests/components/class-admin-interface-test.php
tests/components/class-multilingual-support-test.php

Fixes #326.
- Moves all function calls accessing translated strings to the `init` hook.
- Caches untranslated language names separately for use in multilingual support.

Ensure i18n functions are called during 'init' at the earliest
